### ISSUE TITLE
Use an experimental branch

### ISSUE THREAD

**Issue by alexpghayes** [RoheLab/vsp#47]
@karlrohe I fairly strongly recommend having a separate "experimental" branch where we implement stuff that we know is a good idea but haven't proven yet / haven't put in a paper yet. It's fairly disconcerting when a paper says "here do this" and then the accompanying software does something different, even if mildly different. At least, it is a red flag from a software engineering perspective, one that I think we should try to avoid.

**Comment by karlrohe** [comment]
If you are referring to the varimax on both... 

Students are using the code and it is giving bad results.  I did test it on my machine.  I wanted to put it in fast and didn't want to fuck up other stuff.  Doing a line edit was safer imo.

on the specifics of the problem...  for any given varimax problem, there are k! 2^k different rotation matrices that obtain the exact same optimum value and form an equivalence class among all permutation/sign-flip matrices.  this usually isn't a problem.  you can pick any one that you want!  they are all good!  the problem is that if you permute the columns of Y, then the jth column doesn't align with the jth column of Z.  this makes interpretation really really hard.  doing varimax on rbind(U,V), *before* doing it individually on U and V is a way of helping them to pick the same permutation of columns.  Assuming that varimax finds a solution... It doesn't change anything about the theory.  If varimax does not actually find the optimum, then we have other problems.

**Comment by karlrohe** [comment]
oooookkkkkaaaayy... you were right.  I made two bad typos in that code. 

How do we merge with karlrohe/vsp-1/R/vsp.R?  I made three changes in rohelab version to vsp.R that will conflict.  They should be overwritten.  It might only show 2 conflicts.

**Comment by alexpghayes** [comment]
You'll want to open a pull request to merge these into the master branch. If you don't know how to do this I can walk you through it during our call tomorrow!

**Comment by alexpghayes** [comment]
Pretty sure this code got integrated and then removed after the fact after deciding it wasn't a good idea, or at least not enough to live on the main branch. Closing for now; can revisit this idea on an experimental branch down the line!
