### ISSUE TITLE
refactoring a bit for pairs plots

### ISSUE THREAD

**Issue by karlrohe** [RoheLab/vsp#58]
there is a function get_varimax_y and get_varimax_z.  Perhaps Z, Y, U, and V should all be processed like that *inside of vsp*.  

Moreover, give Z and U row names from rownames(A) and Y, V row names from colnames(A).  Is this tidy verse friendly?  Or should we make a column in the factor matrices that gives the name?  

Similarly, we should name the rows of B z1, ..., zk and the columns of B y1, ..., yk.  

Then, the pairs plot could take just one argument:  (fa$U[,factors]) or three arguments (fa, U, factors).  It is sometimes helpful to see fa$U and V for diagnostic purposes.  

When we make the pairs plot, the upper triangle of panels gives the correlations.  This is not so interesting for vsp.  Is it possible to put the plots also in the upper triangle? 

```
y <- as.matrix(x$Y)
colnames(y) <- paste0("y", 1:x$k)
as_tibble(y)
```

**Comment by alexpghayes** [comment]
Two separate issues here.

1. Should `Z, B, Y, u, d, v` in the `vsp` object be stored as data frames rather than tibbles

I think this should be a bad idea. It's traditional for objects to contain math/computation friendly objects for advanced users, and to provide accessors like `get_varimax_*()` to get objects in nicer formats. In particular, for large factorizations, type conversations can be expensive, and having to go tibble -> matrix every time you want to do a new computation might become irritating (additionally tibble <-> matrix conversation utilities aren't very complete at the moment). We could definitely consider renaming to make it clearer that what you're getting from these is a tibble rather than a matrix?

2. Row names and column names

I started a little on this at https://github.com/RoheLab/vsp/blob/master/R/object.R#L40-L61, but currently the row names and col names helpers are only surfaced to `vsp_fa()`, which constructs the `vsp` object, rather than the mainline `vsp` function. So the TODO here is to surface that functionality up to `vsp()` and additionally consider allowing users to set the community names themselves.

A second followup is then to allow users to specify factors by the factor names; the right approach here is probably to write a helper function.

**Comment by alexpghayes** [comment]
Users should now be able to name rows and columns. See #62 for additional followup on how to store the embeddings.
