### ISSUE TITLE
tidy() methods for embeddings?

### ISSUE THREAD

**Issue by alexpghayes** [RoheLab/vsp#62]
i.e. what is the workflow that `tidytext` uses and what tools should we provide so that users can work with `Y` and `Z` most conveniently. At the moment `Y` and `Z` are `n x k` matrices containing embeddings for each of `n` items. `get_varimax_y()` and `get_varimax_z()` get this data in a dataframe, but I think `tidytext` idioms use the long format for embeddings a lot? @EmilHvitfeldt do you have thoughts or recommendations?

**Comment by EmilHvitfeldt** [comment]
If you are using `tidytext` then you properly want to get to a long format like so:

```r
## # A tibble: 747,500 x 3
##    item1   dimension   value
##    <chr>       <int>   <dbl>
##  1 systems         1 0.0165 
##  2 inc             1 0.0191 
##  3 is              1 0.0202 
##  4 trying          1 0.0423 
##  5 to              1 0.00904
##  6 collect         1 0.0370 
##  7 a               1 0.0126 
##  8 debt            1 0.0430 
##  9 that            1 0.0136 
## 10 not             1 0.0213 
## # … with 747,490 more rows
```

these work well with dplyr, tidytext, stringr etc.

In [textrecipes](https://textrecipes.tidymodels.org/) and [wordsalad](https://github.com/EmilHvitfeldt/wordsalad) I have used wide formats because they are very close simple matrix formats.

In the end, it doesn't matter much which style you pick since it is very easy to go from wide to long. The main thing you have to think about is what package you expect to handle the output of `get_varimax_y()`

**Comment by alexpghayes** [comment]
Deciding that we don't need this for now since `get_varimax_y()`, etc, give nice and tidy data, just in wide format.
